### ISSUE TITLE
Compilation fails with OS_ID=0.4.4

### ISSUE THREAD

**Issue by rebolbot** [rebol/rebol-issues#2125]
_Submitted by:_ **giuliolunati**

Compilation fails with
Linux 3.0.0-12-generic #20-Ubuntu SMP Fri Oct 7 14:56:25 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux

``` rebol
make make OS_ID=0.4.4
make prep
make
```

ERROR:

``` rebol
../src/core/m-gc.c: In function Mark_Devices: 
../src/core/m-gc.c:197:29: error: REBOL_HOST_LIB has no member named devices 
```

GIT BISECT LOG:

``` rebol
git bisect start
# bad: [25033f897b2bd466068d7663563cd3ff64740b94] Merge pull request #186 from BrianHawley/fix-2109-function-local-not-at-end
git bisect bad 25033f897b2bd466068d7663563cd3ff64740b94
# good: [aa7f6c62df1e28b8082007d9432ab1330051e210] Merge pull request #82 from BrianHawley/fix-1952-do-binary
git bisect good aa7f6c62df1e28b8082007d9432ab1330051e210
# good: [fc518bc8350d4895df87e9b81195a0ae231faa16] Merge pull request #185 from BrianHawley/wish-2077-no-if-else
git bisect good fc518bc8350d4895df87e9b81195a0ae231faa16
# bad: [327e130eb0843c9aa064686591b1603890f3495c] Merge pull request #191 from earl/build-android-cli
git bisect bad 327e130eb0843c9aa064686591b1603890f3495c
# good: [0b29e80a26e9154d64858c1ba45c769a3ba30ac4] Merge pull request #194 from cyphre/do-codec-fix
git bisect good 0b29e80a26e9154d64858c1ba45c769a3ba30ac4
# good: [f9aad8722dd8720ca7031edb9ed9d22c16dc19f1] Make the S_IREAD/S_WRITE comment slightly more specific
git bisect good f9aad8722dd8720ca7031edb9ed9d22c16dc19f1
# bad: [5790b26a245e3ed7d5bdbe0342f127dee7987818] Merge pull request #188 from cyphre/9910-port-crash-fix
git bisect bad 5790b26a245e3ed7d5bdbe0342f127dee7987818
```

So offending commit seems:

``` rebol
commit 003ae5d46df8e183c1d2a41fcbaa497345af2d00 
```

Author: Richard Smolak rsmolak@gmail.com 
Date: Thu Feb 20 23:27:55 2014 +0100 

Anyone can confirm? 

<sup>**CC - Data** [ Version: r3 master Type: Bug Platform: Linux x86 libc6 Category: Platform Reproduce: Always Fixed-in:none ]</sup>
